version: "3.8"

services:
  whatsapp-service:
    build: .
    container_name: barlink-whatsapp-service
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - ALLOWED_ORIGINS=https://your-vercel-app.vercel.app,https://your-domain.com
    volumes:
      # Persist WhatsApp session data
      - whatsapp_sessions:/usr/src/app/.wwebjs_auth
      # Persist logs
      - ./logs:/usr/src/app/logs
    networks:
      - whatsapp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # Resource limits for 1GB VPS
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
        reservations:
          memory: 256M
          cpus: "0.25"

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: barlink-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro # SSL certificates if you have them
    depends_on:
      - whatsapp-service
    networks:
      - whatsapp-network
    # Uncomment if you want to use nginx
    # profiles:
    #   - with-nginx

volumes:
  whatsapp_sessions:
    driver: local

networks:
  whatsapp-network:
    driver: bridge
